### PR TITLE
change cursor on handles in drag mode (can be disabled)

### PR DESCRIPTION
**Pull request by catwell**

### CODE REVIEW

**Comment by edgarGracia** [comment]
Thanks for the contributions, really good work!

**Comment by catwell** [comment]
Thank you, we needed a component fot this and this is the best we found :) We should post a HF using it soon.

**Comment by catwell** [comment]
[The space is live](https://huggingface.co/spaces/finegrain/finegrain-object-eraser) :)

We use this component in the 2nd tab ("By bounding box").

**Comment by edgarGracia** [comment]
Very nice project!! I'm glad this helped you :)

**Pull request merged**
